# Application Properties
server.servlet.context-path = /blogger

# Security Properties
spring.security.user.secret    = i-live-here-in-my-perfectly-constructed-loophole-of-self-insanity
spring.security.token.issuer   = blogger-rest
spring.security.token.subject  = user details
spring.security.token.audience = blogger-ui

# Datasource Properties (H2 in-memory for testing)
spring.datasource.url=jdbc:h2:mem:blogger_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.database=blogger_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schemas/users.sql,classpath:schemas/posts.sql,classpath:schemas/comments.sql
# Mongo Properties
spring.data.mongodb.host     = 127.0.0.1
spring.data.mongodb.port     = 27017
spring.data.mongodb.client   = mongodb://127.0.0.1:27017
spring.data.mongodb.database = bloggerDB
spring.data.mongodb.url      = mongodb://127.0.0.1:27017/bloggerDB
spring.data.mongodb.username = wulf
spring.data.mongodb.password = wulf123

# JPA Properties (For Future Use)
spring.jpa.show-sql                                    = true
spring.jpa.properties.hibernate.dialect                = org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine = innodb
spring.jpa.hibernate.ddl-auto                          = update
